/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface Error {
  error: string;
}

export interface Student {
  id: number;
  fullName: string;
  registerNumber: string;
  email: string;
  /** @nullable */
  phoneNumber: string | null;
  /** @nullable */
  department: string | null;
  /** @nullable */
  academicYear: string | null;
  /** @nullable */
  gender: string | null;
  /** @nullable */
  dateOfBirth: string | null;
  /** @nullable */
  address: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface StudentInput {
  /** @minLength 1 */
  fullName: string;
  /** @minLength 1 */
  registerNumber: string;
  email: string;
  /**
     * @nullable
     * @pattern ^[0-9+()\-\s]{7,20}$
     */
  phoneNumber?: string | null;
  /** @nullable */
  department?: string | null;
  /** @nullable */
  academicYear?: string | null;
  /** @nullable */
  gender?: string | null;
  /** @nullable */
  dateOfBirth?: string | null;
  /** @nullable */
  address?: string | null;
}

export interface StudentUpdate {
  /** @minLength 1 */
  fullName?: string;
  /** @minLength 1 */
  registerNumber?: string;
  email?: string;
  /**
     * @nullable
     * @pattern ^[0-9+()\-\s]{7,20}$
     */
  phoneNumber?: string | null;
  /** @nullable */
  department?: string | null;
  /** @nullable */
  academicYear?: string | null;
  /** @nullable */
  gender?: string | null;
  /** @nullable */
  dateOfBirth?: string | null;
  /** @nullable */
  address?: string | null;
}

export interface DepartmentCount {
  department: string;
  count: number;
}

export interface StudentSummary {
  totalStudents: number;
  departmentCounts: DepartmentCount[];
  recentStudents: Student[];
}

export type ListStudentsParams = {
search?: string;
department?: string;
};

